name: Crypt4GH Middleware Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install requirements
        run: pip install -r requirements_dev.txt
      - name: Lint with pylint
        run: pylint tests/tasks/* middleware/*
      - name: Lint with ruff
        run: ruff check tests/tasks/* middleware/*
      - name: Type checking with mypy
        run: mypy middleware
