name: Crypt4GH Middleware Checks

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Lint with pylint
        run: poetry run pylint tests/* crypt4gh_middleware/*
      - name: Lint with ruff
        run: poetry run ruff check tests/* crypt4gh_middleware/*
      - name: Type checking with mypy
        run: poetry run mypy crypt4gh_middleware
